// GÉNÉRÉ PAR tools/koach/build_koach.py (lot GK) — NE PAS MODIFIER À LA MAIN.
// Sources : tools/koach/sources/ (empreintes SHA-256 dans build_koach.py).
// Format des commandes : voir CONTRAT.md (§ Format des commandes).
// dart format off

import '../koach_pose.dart';

/// Fiches des 36 poses, dans l’ordre de [KoachPose.values].
const List<KoachPoseInfo> koachPoseInfos = <KoachPoseInfo>[
  KoachPoseInfo(
    id: 'explain_board',
    sheet: 'A',
    row: 0,
    col: 0,
    emotion: KoachEmotion.explaining,
    usages: <KoachUsage>[KoachUsage.explanation, KoachUsage.program, KoachUsage.review],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'read_tip',
    sheet: 'A',
    row: 0,
    col: 1,
    emotion: KoachEmotion.explaining,
    usages: <KoachUsage>[KoachUsage.tip, KoachUsage.explanation, KoachUsage.featureIntro],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'anatomy',
    sheet: 'A',
    row: 0,
    col: 2,
    emotion: KoachEmotion.explaining,
    usages: <KoachUsage>[KoachUsage.explanation, KoachUsage.exercise],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'progress_chart',
    sheet: 'A',
    row: 1,
    col: 0,
    emotion: KoachEmotion.proud,
    usages: <KoachUsage>[KoachUsage.progress, KoachUsage.record, KoachUsage.goal],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'think',
    sheet: 'A',
    row: 1,
    col: 1,
    emotion: KoachEmotion.thinking,
    usages: <KoachUsage>[KoachUsage.why, KoachUsage.question, KoachUsage.profile],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'checklist',
    sheet: 'A',
    row: 1,
    col: 2,
    emotion: KoachEmotion.explaining,
    usages: <KoachUsage>[KoachUsage.profile, KoachUsage.review, KoachUsage.healthCheck],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'choice',
    sheet: 'A',
    row: 2,
    col: 0,
    emotion: KoachEmotion.thinking,
    usages: <KoachUsage>[KoachUsage.decision, KoachUsage.proposal],
    eyesOpen: true,
    framing: KoachFraming.bust,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'idea',
    sheet: 'A',
    row: 2,
    col: 1,
    emotion: KoachEmotion.curious,
    usages: <KoachUsage>[KoachUsage.tip, KoachUsage.featureIntro],
    eyesOpen: true,
    framing: KoachFraming.bust,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'settings',
    sheet: 'A',
    row: 2,
    col: 2,
    emotion: KoachEmotion.explaining,
    usages: <KoachUsage>[KoachUsage.settings, KoachUsage.devSession, KoachUsage.adjustment],
    eyesOpen: true,
    framing: KoachFraming.bust,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'determined',
    sheet: 'A',
    row: 3,
    col: 0,
    emotion: KoachEmotion.determined,
    usages: <KoachUsage>[KoachUsage.encouragement, KoachUsage.sessionStart],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.right,
  ),
  KoachPoseInfo(
    id: 'direction',
    sheet: 'A',
    row: 3,
    col: 1,
    emotion: KoachEmotion.explaining,
    usages: <KoachUsage>[KoachUsage.program, KoachUsage.nextStep],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'analyze',
    sheet: 'A',
    row: 3,
    col: 2,
    emotion: KoachEmotion.curious,
    usages: <KoachUsage>[KoachUsage.analysis, KoachUsage.calibration, KoachUsage.review],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'wave',
    sheet: 'B',
    row: 0,
    col: 0,
    emotion: KoachEmotion.greeting,
    usages: <KoachUsage>[KoachUsage.welcome, KoachUsage.devSession],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.left,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'thumbs_up',
    sheet: 'B',
    row: 0,
    col: 1,
    emotion: KoachEmotion.approving,
    usages: <KoachUsage>[KoachUsage.confirmation, KoachUsage.success],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.left,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'happy',
    sheet: 'B',
    row: 0,
    col: 2,
    emotion: KoachEmotion.happy,
    usages: <KoachUsage>[KoachUsage.success, KoachUsage.program],
    eyesOpen: false,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.right,
  ),
  KoachPoseInfo(
    id: 'point',
    sheet: 'B',
    row: 1,
    col: 0,
    emotion: KoachEmotion.explaining,
    usages: <KoachUsage>[KoachUsage.nextStep, KoachUsage.explanation],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'ponder',
    sheet: 'B',
    row: 1,
    col: 1,
    emotion: KoachEmotion.thinking,
    usages: <KoachUsage>[KoachUsage.why, KoachUsage.question, KoachUsage.decision],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'shrug',
    sheet: 'B',
    row: 1,
    col: 2,
    emotion: KoachEmotion.unsure,
    usages: <KoachUsage>[KoachUsage.unknown, KoachUsage.cancel],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'oops',
    sheet: 'B',
    row: 2,
    col: 0,
    emotion: KoachEmotion.sorry,
    usages: <KoachUsage>[KoachUsage.error, KoachUsage.cancel],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.left,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'please',
    sheet: 'B',
    row: 2,
    col: 1,
    emotion: KoachEmotion.caring,
    usages: <KoachUsage>[KoachUsage.request, KoachUsage.healthCheck, KoachUsage.rest],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'love',
    sheet: 'B',
    row: 2,
    col: 2,
    emotion: KoachEmotion.caring,
    usages: <KoachUsage>[KoachUsage.thanks, KoachUsage.care, KoachUsage.rest],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'flex',
    sheet: 'B',
    row: 3,
    col: 0,
    emotion: KoachEmotion.proud,
    usages: <KoachUsage>[KoachUsage.record, KoachUsage.progress],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.right,
  ),
  KoachPoseInfo(
    id: 'run',
    sheet: 'B',
    row: 3,
    col: 1,
    emotion: KoachEmotion.energetic,
    usages: <KoachUsage>[KoachUsage.sessionStart, KoachUsage.encouragement],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.right,
  ),
  KoachPoseInfo(
    id: 'victory',
    sheet: 'B',
    row: 3,
    col: 2,
    emotion: KoachEmotion.celebrating,
    usages: <KoachUsage>[KoachUsage.record, KoachUsage.success, KoachUsage.sessionEnd],
    eyesOpen: false,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'thumbs_up_2',
    sheet: 'C',
    row: 0,
    col: 0,
    emotion: KoachEmotion.approving,
    usages: <KoachUsage>[KoachUsage.confirmation, KoachUsage.success],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.right,
  ),
  KoachPoseInfo(
    id: 'cheer',
    sheet: 'C',
    row: 0,
    col: 1,
    emotion: KoachEmotion.celebrating,
    usages: <KoachUsage>[KoachUsage.success, KoachUsage.record],
    eyesOpen: false,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.right,
  ),
  KoachPoseInfo(
    id: 'pump',
    sheet: 'C',
    row: 0,
    col: 2,
    emotion: KoachEmotion.determined,
    usages: <KoachUsage>[KoachUsage.encouragement, KoachUsage.sessionStart],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'flag',
    sheet: 'C',
    row: 0,
    col: 3,
    emotion: KoachEmotion.proud,
    usages: <KoachUsage>[KoachUsage.goal, KoachUsage.progress],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'fist_bump',
    sheet: 'C',
    row: 1,
    col: 0,
    emotion: KoachEmotion.encouraging,
    usages: <KoachUsage>[KoachUsage.encouragement, KoachUsage.welcome],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.right,
  ),
  KoachPoseInfo(
    id: 'heart',
    sheet: 'C',
    row: 1,
    col: 1,
    emotion: KoachEmotion.caring,
    usages: <KoachUsage>[KoachUsage.thanks, KoachUsage.care],
    eyesOpen: false,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'you',
    sheet: 'C',
    row: 1,
    col: 2,
    emotion: KoachEmotion.encouraging,
    usages: <KoachUsage>[KoachUsage.request, KoachUsage.nextStep],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.left,
    bubbleSide: KoachSide.left,
  ),
  KoachPoseInfo(
    id: 'double_biceps',
    sheet: 'C',
    row: 1,
    col: 3,
    emotion: KoachEmotion.proud,
    usages: <KoachUsage>[KoachUsage.record, KoachUsage.progress],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.right,
  ),
  KoachPoseInfo(
    id: 'clap',
    sheet: 'C',
    row: 2,
    col: 0,
    emotion: KoachEmotion.celebrating,
    usages: <KoachUsage>[KoachUsage.sessionEnd, KoachUsage.success],
    eyesOpen: false,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.right,
  ),
  KoachPoseInfo(
    id: 'sprint',
    sheet: 'C',
    row: 2,
    col: 1,
    emotion: KoachEmotion.energetic,
    usages: <KoachUsage>[KoachUsage.sessionStart, KoachUsage.encouragement],
    eyesOpen: true,
    framing: KoachFraming.full,
    gaze: KoachGaze.right,
    bubbleSide: KoachSide.right,
  ),
  KoachPoseInfo(
    id: 'fist_up',
    sheet: 'C',
    row: 2,
    col: 2,
    emotion: KoachEmotion.celebrating,
    usages: <KoachUsage>[KoachUsage.goal, KoachUsage.success],
    eyesOpen: false,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.right,
  ),
  KoachPoseInfo(
    id: 'present',
    sheet: 'C',
    row: 2,
    col: 3,
    emotion: KoachEmotion.welcoming,
    usages: <KoachUsage>[KoachUsage.featureIntro, KoachUsage.welcome, KoachUsage.explanation],
    eyesOpen: false,
    framing: KoachFraming.full,
    gaze: KoachGaze.front,
    bubbleSide: KoachSide.right,
  ),
];
// dart format on
