"""Rattachement des 505 exercices de la base v1 (assets/exercises_db.json.gz) au
schéma v2, et exercices ajoutés (KT-044). Généré par Claude (L9) — à relire.

E(nom_v1, archétype, difficulté, **options)
Options : pose, eq (matériel), charge, mesure, uni, mods (liste), base (nom de
l'exercice dont c'est une variante de méthode ou de charge), doublon (nom v1 du
doublon canonique), nc (non-conformité détectée), role (exercice | test |
hors_generateur), type, prim, sec, nom (nom v2 corrigé), alias.
"""

EX = []


def E(name, arch, diff, **kw):
    EX.append(dict(name=name, arch=arch, diff=diff, **kw))


# ------------------------------------------------------------------ A – C
E("Ab wheel", "ab_wheel", 6, alias=["roue abdominale à genoux"])
E("Ab wheel debout", "ab_wheel", 9, pose="genoux.ab_wheel", nc="Matériel v1 « poids de corps » : une roue est nécessaire.")
E("Abducteurs machine", "abducteurs", 1)
E("Adducteurs machine", "adducteurs_machine", 1)
E("Arch rocks", "superman", 3, mesure="repetitions")
E("Archer rows anneaux", "rowing_anneaux", 7, uni=True)
E("Around the world (suspendu)", "windshield", 8)
E("Assault bike", "ergo_velo", 2, nc="Matériel v1 « poids de corps » : ergomètre nécessaire.", doublon="Echo bike (calories)")
E("Assault bike — sprints", "ergo_velo", 5, mods=["sprint"], base="Assault bike")
E("ATR (équilibre)", "atr", 7)
E("ATR dos au mur (tenue)", "atr_dos_mur", 4)
E("ATR poitrine au mur (tenue)", "atr_poitrine_mur", 5)
E("Australian pull-ups (rows barre basse)", "rowing_australien", 2)
E("Back lever advanced tuck", "back_lever", 7, pose="levier.back_adv")
E("Back lever complet", "back_lever", 9, pose="levier.back_full")
E("Back lever straddle", "back_lever", 8, pose="levier.back_straddle")
E("Back lever tuck", "back_lever", 6, pose="levier.back_tuck")
E("Back squat", "squat_barre", 4)
E("Bar dips (dips à la barre fixe)", "dips_barre_fixe", 5)
E("Bar dips lestés", "dips_barre_fixe", 6, mods=["leste"], base="Bar dips (dips à la barre fixe)")
E("Battle ropes", "battle_rope", 3)
E("Bear crawl", "crawl", 3)
E("Bicycle crunchs", "crunch", 2, type="gainage_anti_rotation", prim="abdominaux obliques")
E("Bilan", "respiration", 1, role="hors_generateur", type="hors_categorie",
  nc="Entrée de suivi (report de résultats), pas un exercice.")
E("Bird dog", "bird_dog", 1)
E("Body saw (sliders)", "body_saw", 4)
E("Box jumps", "box_jump", 4)
E("Box jumps step-down", "box_jump", 3, alias=["box jump redescente en marchant"])
E("Box squat", "box_squat", 4)
E("Box step-overs", "step_up", 3, type="conditionnement", eq=["box"])
E("Bridge (pont dorsal)", "pont_dorsal", 5)
E("Broad jumps (sauts en longueur)", "saut", 4, pose="saut.longueur")
E("Burpees", "burpee", 4)
E("Burpees box jump-over", "burpee", 6, eq=["box"])
E("Burpees broad jump", "burpee", 5)
E("Burpees lestés (gilet)", "burpee", 6, mods=["leste"], base="Burpees")
E("Burpees over the bar", "burpee", 5, eq=["barre"])
E("Burpees pull-up", "burpee", 6, eq=["barre_fixe"])
E("Butterfly pull-ups", "traction_kipping", 8)
E("Chest-to-bar kipping", "traction_kipping", 7)
E("Chin-up lesté", "traction", 7, mods=["leste"], base="Traction supination")
E("Ciseaux (scissors)", "flutter", 2)
E("Clamshell élastique", "clamshell", 1)
E("Clean & jerk", "clean", 9, pose="olympique.clean_press")
E("Contraste français", "respiration", 5, role="hors_generateur", type="hors_categorie",
  nc="Méthode d'entraînement (enchaînement lourd puis explosif), pas un exercice ; le programme l'associe au squat et au muscle-up.")
E("Copenhagen plank", "copenhague", 5)
E("Corde à sauter", "corde_a_sauter", 2, nc="Matériel v1 « poids de corps » : corde nécessaire.", eq=["corde_a_sauter"])
E("Course à pied (footing)", "course", 3)
E("Course — fartlek", "course", 4, mods=["intervalles"], base="Course à pied (footing)")
E("Course — fractionné 200 m", "sprint", 6, base="Course à pied (footing)")
E("Course — fractionné 400 m", "sprint", 6, base="Course à pied (footing)")
E("Crab walk", "crab_walk", 3)
E("Crunchs inversés", "relevé_jambes", 2, pose="dos_au_sol.leg_raise")
E("Crunchs lestés", "crunch", 3, mods=["leste"], base="Crunchs inversés", eq=["disques"])
E("Crunchs poulie haute", "crunch_poulie", 3)
E("Cuban press", "cuban_press", 3)
E("Curl araignée", "curl", 3, eq=["halteres", "banc"])
E("Curl barre EZ", "curl_barre", 2)
E("Curl concentration", "curl", 2, uni=True)
E("Curl élastique", "curl", 1, charge="elastique", eq=["elastique"])
E("Curl haltères", "curl", 2)
E("Curl incliné", "curl", 3, eq=["halteres", "banc"])
E("Curl marteau", "curl_marteau", 2)
E("Curl marteau (par haltère)", "curl_marteau", 2, doublon="Curl marteau")
E("Curl poignet", "poignet_flexion", 1)
E("Curl poulie basse", "curl_poulie", 2)
E("Curl pronation (reverse curl)", "curl_barre", 3, prim="avant_bras biceps")
E("Curl pupitre (Larry Scott)", "curl_pupitre", 3)
E("Curl Zottman", "curl", 3, prim="biceps avant_bras")
# ------------------------------------------------------------------ D
E("Dead bug", "dead_bug", 1)
E("Dead-hang", "dead_hang", 1)
E("Dead-hang lesté ou PdC", "dead_hang", 3, mods=["leste_optionnel"], base="Dead-hang",
  nc="Nom ambigu (« lesté ou PdC ») : deux modes de charge dans une seule entrée.")
E("Dead-hang serviette", "dead_hang", 4, eq=["barre_fixe", "serviette"])
E("Dead-hang une main", "dead_hang", 6, uni=True)
E("Développé Arnold", "developpe_halteres", 4)
E("Développé couché", "developpe_couche", 3)
E("Développé couché haltères", "developpe_couche_halteres", 3)
E("Développé couché pause", "developpe_couche", 4, mods=["pause"], base="Développé couché", pose="banc.pause")
E("Développé couché prise serrée", "developpe_couche", 4, prim="triceps pectoraux")
E("Développé décliné", "developpe_couche", 4)
E("Développé haltères assis", "developpe_assis", 3)
E("Développé incliné", "developpe_incline", 3)
E("Développé incliné haltères", "developpe_incline", 3, charge="halteres", eq=["halteres", "banc"])
E("Développé kettlebell (par bras)", "developpe_halteres", 4, charge="kettlebell", eq=["kettlebell"], uni=True)
E("Développé militaire assis", "developpe_assis", 4, charge="barre", eq=["barre", "banc", "rack"])
E("Développé militaire debout", "developpe_militaire", 4)
E("Développé militaire haltères debout", "developpe_halteres", 3)
E("Devil press", "devil_press", 6)
E("Dip", "dips_barres", 5, doublon="Dips")
E("Dip Lesté", "dips_barres", 6, mods=["leste"], base="Dips", doublon="Dips lestés")
E("Dips", "dips_barres", 5)
E("Dips à résistance accommodante (élastique depuis le sol)", "dips_barres", 7, mods=["elastique_resistance"], base="Dips",
  eq=["barres_paralleles", "elastique"])
E("Dips assistés élastique", "dips_barres", 3, mods=["assiste"], base="Dips", eq=["barres_paralleles", "elastique"],
  nc="Matériel v1 « élastique » seul : les barres parallèles sont aussi nécessaires.")
E("Dips aux anneaux", "dips_anneaux", 7, nc="Groupe v1 « dos, pectoraux » : le dos n'est pas moteur.")
E("Dips aux anneaux lestés", "dips_anneaux", 8, mods=["leste"], base="Dips aux anneaux")
E("Dips aux anneaux RTO (tournés)", "dips_anneaux", 8)
E("Dips bulgares (prise large)", "dips_barres", 6, prim="pectoraux triceps", precautions_plus=["epaule_anterieure"])
E("Dips coréens", "dips_barre_fixe", 8, pose="dips.barre_fixe", precautions_plus=["epaule_anterieure"])
E("Dips excentriques lestés", "dips_barres", 6, mods=["leste", "negatif"], base="Dips lestés")
E("Dips explosifs", "dips_barres", 6, mods=["explosif"], base="Dips")
E("Dips isométriques mi-course", "iso_dips", 4, base="Dips")
E("Dips lestés", "dips_barres", 6, mods=["leste"], base="Dips")
E("Dips lestés cluster", "dips_barres", 6, mods=["leste", "clusters"], base="Dips lestés")
E("Dips lestés pause", "dips_barres", 6, mods=["leste", "pause"], base="Dips lestés")
E("Dips lestés tempo", "dips_barres", 6, mods=["leste", "tempo"], base="Dips lestés")
E("Dips lestés — singles lourds", "dips_barres", 7, mods=["leste", "singles_lourds"], base="Dips lestés")
E("Dips négatifs", "dips_barres", 3, mods=["negatif"], base="Dips")
E("Dips pause basse", "dips_barres", 5, mods=["pause"], base="Dips")
E("Dips PdC", "dips_barres", 5, doublon="Dips")
E("Dips sur banc (triceps)", "dips_banc", 3)
E("Dips tempo (3 s excentrique)", "dips_barres", 5, mods=["tempo"], base="Dips")
E("Dislocations épaules bâton", "dislocations", 1)
E("Dislocations épaules élastique", "dislocations", 1, eq=["elastique"])
E("Double-unders", "corde_a_sauter", 5)
E("Dragon flag (progression)", "dragon_flag", 7)
E("Dragon flag complet", "dragon_flag", 9)
E("Dragon flag négatif", "dragon_flag", 7, mods=["negatif"], base="Dragon flag complet")
# ------------------------------------------------------------------ E – F
E("Écarté haltères", "ecarte", 3)
E("Écarté poulie vis-à-vis", "ecarte_poulie", 2)
E("Echo bike (calories)", "ergo_velo", 3)
E("Élévations en ATR (tenue)", "atr_poitrine_mur", 6, nc="Intitulé imprécis : interprété comme montées en ATR contre le mur avec tenue.")
E("Élévations frontales", "elevation_frontale", 2)
E("Élévations latérales", "elevation_laterale", 2)
E("Élévations latérales (par haltère)", "elevation_laterale", 2, doublon="Élévations latérales")
E("Élévations latérales élastique", "elevation_laterale", 1, charge="elastique", eq=["elastique"])
E("Élévations latérales poulie", "elevation_laterale", 2, charge="poulie", eq=["poulie"], uni=True)
E("Enrouleur de poignet (wrist roller)", "wrist_roller", 3)
E("Étirements chaîne postérieure", "etirement_posterieur", 1)
E("Étirements fléchisseurs de hanche", "etirement_flechisseurs", 1)
E("Excentrique de transition muscle-up", "muscle_up_negatif", 6, base="Muscle-up")
E("Excentriques de transition LESTÉS", "muscle_up_negatif", 7, mods=["leste"], base="Excentrique de transition muscle-up")
E("Extension corde", "extension_triceps_poulie", 2, doublon="Extension triceps poulie corde")
E("Extension poignet", "poignet_flexion", 1)
E("Extension poignet barre", "poignet_flexion", 1, charge="barre", eq=["barre"])
E("Extension triceps couché (barre EZ)", "barre_front", 3, doublon="Barre au front EZ")
E("Extension triceps haltère à deux mains", "extension_triceps_nuque", 3)
E("Extension triceps nuque", "extension_triceps_nuque", 3)
E("Extension triceps poulie", "extension_triceps_poulie", 2)
E("Extension triceps poulie corde", "extension_triceps_poulie", 2)
E("Extension triceps unilatérale poulie", "extension_triceps_poulie", 2, uni=True)
E("Extensions de doigts élastique", "extension_doigts", 1)
E("Face pulls", "face_pull", 2)
E("Face pulls aux anneaux", "rowing_anneaux", 3, prim="deltoide_posterieur coiffe_rotateurs rhomboides", pose="cable.face_pull")
E("Face pulls élastique", "face_pull", 1, charge="elastique", eq=["elastique"])
E("False grip hang", "false_grip", 5, eq=["barre_fixe"])
E("False grip hold (anneaux ou barre)", "false_grip", 5, eq=["anneaux"], alias=["false grip hold barre"])
E("Farmer hold (tenue)", "farmer_hold", 2)
E("Farmer walk", "farmer", 2)
E("Farmer walk kettlebells", "farmer", 2, charge="kettlebell", eq=["kettlebell"])
E("Farmer walk lourd (trap bar)", "farmer", 4, charge="barre", eq=["barre"])
E("Fentes arrière", "fente", 2)
E("Fentes avant", "fente", 3)
E("Fentes bulgares", "fente_bulgare", 5)
E("Fentes déficit", "fente", 4, eq=["support_stable"])
E("Fentes latérales", "fente_laterale", 3)
E("Fentes marchées", "fente", 3, type="fente")
E("Fentes marchées (par haltère)", "fente", 4, charge="halteres", eq=["halteres"], doublon="Fentes marchées haltères",
  nc="Matériel v1 « poids de corps » alors que l'exercice est chargé en haltères.")
E("Fentes marchées haltères", "fente", 4, charge="halteres", eq=["halteres"])
E("Fentes marchées lestées (sac)", "fente", 4, charge="objet_leste", eq=["sac_leste"])
E("Fentes sautées", "fente_sautee", 5)
E("Floor press", "floor_press", 3)
E("Flutter kicks", "flutter", 2)
E("Foam roller (auto-massage)", "foam", 1)
E("Front lever advanced tuck", "front_lever", 7, pose="levier.front_adv")
E("Front lever complet", "front_lever", 10, pose="levier.front_full")
E("Front lever hold à l'élastique", "front_lever", 6, mods=["assiste"], base="Front lever complet", eq=["barre_fixe", "elastique"],
  pose="levier.front_straddle")
E("Front lever négatif", "front_lever_dyn", 8, mods=["negatif"], base="Front lever complet", pose="levier.front_straddle.dynamique")
E("Front lever one leg", "front_lever", 8, pose="levier.front_one")
E("Front lever pull-ups (tuck)", "front_lever_dyn", 8, pose="levier.front_tuck.dynamique")
E("Front lever raises", "front_lever_dyn", 7, pose="levier.front_adv.dynamique")
E("Front lever straddle", "front_lever", 9, pose="levier.front_straddle")
E("Front lever tuck", "front_lever", 6, pose="levier.front_tuck")
E("Front squat", "front_squat", 5)
# ------------------------------------------------------------------ G – K
E("German hang (tenue)", "german_hang", 6, eq=["barre_fixe"])
E("Good mornings", "good_morning", 5, nc="Groupe v1 « quadriceps, fessiers » : les moteurs sont les ischio-jambiers et les érecteurs.")
E("Hack squat", "hack_squat", 3)
E("Half burpees", "burpee", 3, alias=["burpee sans saut ni pompe"])
E("Hand gripper", "prehension", 1, nc="Matériel v1 « poids de corps » : pince de préhension nécessaire.")
E("Handstand push-ups (mur)", "hspu", 7)
E("Handstand walk (marche en ATR)", "handstand_walk", 8)
E("Hang clean", "clean", 6)
E("High knees (montées de genoux)", "genoux_hauts", 2)
E("HIIT course 30/30", "sprint", 5, mesure="temps", base="Course à pied (footing)")
E("HIIT court", "burpee", 4, role="hors_generateur", type="conditionnement",
  nc="Format de séance générique sans exercice défini ; représenté par une pose de burpee.")
E("Hip thrust", "hip_thrust", 3)
E("Hip thrust unilatéral", "hip_thrust", 4, uni=True, charge="poids_de_corps", eq=["banc"])
E("Hollow body hold", "hollow", 3)
E("Hollow hold lesté", "hollow", 5, mods=["leste"], base="Hollow body hold", eq=["disques"])
E("Hollow rocks", "hollow_rocks", 4)
E("HSPU freestanding (progression)", "hspu", 9, eq=["aucun"], precautions_plus=["equilibre", "chute_arriere"])
E("HSPU kipping", "hspu", 7, precautions_plus=["technique_prioritaire"])
E("HSPU stricts en déficit", "hspu", 8, eq=["mur", "poignees"])
E("Human flag (drapeau)", "drapeau", 9, pose="drapeau.full", nc="Matériel v1 « poids de corps » : un poteau vertical ou un espalier est nécessaire.")
E("Human flag tuck", "drapeau", 7, pose="drapeau.tuck")
E("Hyperextensions (banc 45°)", "hyperextension", 2)
E("Ice cream makers", "front_lever_dyn", 8, pose="levier.front_tuck.dynamique")
E("Inchworms", "inchworm", 2)
E("Isométrie bas de dip", "iso_dips", 5)
E("Isométrie maximale", "iso_dips", 6, doublon="Isométrie bas de dip",
  nc="Intitulé générique : le programme l'emploie pour deux positions (bas de dip, transition de muscle-up), séparées en v2.")
E("Jefferson curl", "jefferson", 6)
E("JM press", "barre_front", 5, pose="banc.couche")
E("Jumping jacks", "jumping_jacks", 1)
E("Kettlebell clean", "clean_press", 4, pose="olympique.clean")
E("Kettlebell clean & press", "clean_press", 5)
E("Kettlebell snatch", "kb_snatch", 7)
E("Kettlebell swing", "swing", 4)
E("Kettlebell swing une main", "swing", 5, uni=True)
E("Kettlebell windmill", "windmill", 6)
E("Kick-back fessiers poulie", "kick_back_poulie", 2)
E("Kickback triceps", "kickback", 2)
E("Kipping pull-ups", "traction_kipping", 6)
E("Knee raises suspendu", "suspension_genoux", 3)
E("Knees to elbows", "toes_to_bar", 5, pose="suspension.knee_raise.barre_fixe")
# ------------------------------------------------------------------ L
E("L-sit", "lsit", 5)
E("L-sit à la barre fixe (tenue)", "lsit", 5, pose="suspension.l_sit_barre.barre_fixe", eq=["barre_fixe"], contrainte="21100000")
E("L-sit au sol (tenue)", "lsit", 6, pose="lsit.sol", eq=["aucun"])
E("L-sit tuck (tenue)", "lsit_tuck", 3)
E("Landmine press", "landmine_press", 3, uni=True)
E("Landmine rotations", "landmine_rotation", 5)
E("Leg curl", "leg_curl_machine", 2)
E("Leg curl sliders", "leg_curl_sol", 4)
E("Leg curl swiss ball", "leg_curl_sol", 3, eq=["swiss_ball"])
E("Leg extension", "leg_extension", 1)
E("Leg raises lestés", "relevé_jambes", 5, mods=["leste"], base="Relevés de jambes au sol", eq=["halteres"])
E("Leg raises lestés (suspendu)", "suspension_jambes", 7, mods=["leste"], base="Leg raises suspendu")
E("Leg raises suspendu", "suspension_jambes", 5, nc="Matériel v1 « poids de corps » : barre fixe nécessaire.")
# ------------------------------------------------------------------ M
E("Man makers", "man_maker", 7)
E("Manna progression", "manna", 10)
E("Marche de récupération", "marche", 1)
E("Marche latérale élastique (monster walk)", "monster_walk", 1)
E("Marche lestée (ruck)", "marche_lestee", 3)
E("Marche ou vélo très léger", "marche", 1, role="hors_generateur",
  nc="Deux activités dans une seule entrée ; consigne de récupération plus qu'exercice.")
E("Marche rapide", "marche", 2, type="locomotion")
E("Mobilité complète", "mobilite_complete", 1, nc="Routine générique sans contenu défini.")
E("Mobilité épaules + poignets", "mobilite_poignets", 1, eq=["aucun"],
  nc="Matériel v1 « haltères » pour une routine de mobilité sans charge.")
E("Mobilité hanches (90/90)", "mobilite_hanches", 1)
E("Mobilité thoracique (cat-cow, rotations)", "mobilite_thoracique", 1)
E("Mollets assis", "mollets_assis", 1)
E("Mollets debout", "mollets", 2, charge="machine", eq=["machine"])
E("Mollets debout barre", "mollets", 2, charge="barre", eq=["barre", "rack"])
E("Mollets sur presse", "mollets", 2, charge="machine", eq=["machine"], pose="assis.calf_seated")
E("Mollets unilatéraux sur marche", "mollets_unijambe", 2)
E("Mountain climbers", "mountain_climbers", 3)
E("Muscle-up", "muscle_up", 8)
E("Muscle-up aux anneaux", "muscle_up_anneaux", 8)
E("Muscle-up aux anneaux strict", "muscle_up_anneaux", 9)
E("Muscle-up kipping", "muscle_up", 7)
E("Muscle-up lesté", "muscle_up", 9, mods=["leste"], base="Muscle-up strict")
E("Muscle-up lesté cluster", "muscle_up", 9, mods=["leste", "clusters"], base="Muscle-up lesté")
E("Muscle-up lesté — singles", "muscle_up", 10, mods=["leste", "singles_lourds"], base="Muscle-up lesté")
E("Muscle-up négatif lesté", "muscle_up_negatif", 8, mods=["leste"], base="Négatifs de muscle-up")
E("Muscle-up strict", "muscle_up", 9)
# ------------------------------------------------------------------ N – O
E("Négatif de muscle-up", "muscle_up_negatif", 6, doublon="Négatifs de muscle-up")
E("Négatifs de muscle-up", "muscle_up_negatif", 6)
E("Négatifs de muscle-up complets", "muscle_up_negatif", 6, doublon="Négatifs de muscle-up")
E("Nordic curl (excentrique)", "nordic", 7, nc="Groupe v1 « quadriceps, fessiers » : le moteur est l'ischio-jambier.")
E("Nordic curl assisté élastique", "nordic", 5, mods=["assiste"], base="Nordic curl (excentrique)", eq=["support_stable", "elastique"])
E("Oiseau (élévations buste penché)", "oiseau", 2)
E("Oiseau à la poulie", "oiseau", 2, charge="poulie", eq=["poulie"])
E("Overhead carry", "overhead_carry", 4)
# ------------------------------------------------------------------ P
E("Pallof press", "pallof", 2, charge="poulie", eq=["poulie"])
E("Pallof press élastique", "pallof", 2)
E("Pec deck", "pec_deck", 2)
E("Pike push-ups", "pompe_pike", 4)
E("Pike push-ups surélevés (pieds sur banc)", "pompe_pike", 5, eq=["support_stable"])
E("Pinch grip disques (tenue)", "pinch", 3)
E("Pistol squat", "pistol", 8)
E("Pistol squat assisté", "pistol_assiste", 5)
E("Pistol squat lesté", "pistol", 9, mods=["leste"], base="Pistol squat", eq=["kettlebell"])
E("Planche (gainage)", "planche_coudes", 2, nc="Intitulé ambigu avec la figure « planche » du street workout ; renommé en v2.",
  nom="Planche de gainage sur les coudes")
E("Planche advanced tuck", "planche_skill", 8, pose="planche_skill.adv")
E("Planche avec sortie (walkout)", "inchworm", 3)
E("Planche bras tendus + taps", "planche_bras_tendus", 3, type="gainage_anti_rotation", mesure="repetitions")
E("Planche latérale", "planche_laterale", 2)
E("Planche latérale lestée", "planche_laterale", 4, mods=["leste"], base="Planche latérale", eq=["disques"])
E("Planche lean", "planche_lean", 4)
E("Planche lean à l'élastique", "planche_lean", 3, mods=["assiste"], base="Planche lean", eq=["elastique", "barre_fixe"])
E("Planche lestée (gainage)", "planche_coudes", 4, mods=["leste"], base="Planche (gainage)", eq=["lest"])
E("Planche RKC (coudes)", "planche_rkc", 4)
E("Planche straddle", "planche_skill", 9, pose="planche_skill.straddle")
E("Plate pinch carry", "pinch", 3, mesure="distance")
E("Pompes", "pompe", 3)
E("Pompes à genoux", "pompe_genoux", 2)
E("Pompes archer", "pompe_archer", 6)
E("Pompes aux anneaux", "pompe", 5, eq=["anneaux"], nc="Groupe v1 « dos, pectoraux » : le dos n'est pas moteur.")
E("Pompes aux anneaux RTO", "pompe", 6, eq=["anneaux"])
E("Pompes déclinées", "pompe_declinee", 4)
E("Pompes déficit (poignées)", "pompe", 4, eq=["poignees"])
E("Pompes diamant", "pompe_diamant", 5)
E("Pompes diamant surélevées", "pompe_diamant", 6, eq=["support_stable"])
E("Pompes explosives (clap)", "pompe_explosive", 6)
E("Pompes hindu", "pompe", 4, pose="pompe.pike", prim="pectoraux triceps deltoide_anterieur")
E("Pompes inclinées (mains surélevées)", "pompe_inclinee", 2)
E("Pompes lestées", "pompe", 5, mods=["leste"], base="Pompes", nc="Matériel v1 « poids de corps » : lest nécessaire.")
E("Pompes lestées (lest ajouté)", "pompe", 5, mods=["leste"], base="Pompes", doublon="Pompes lestées")
E("Pompes pause au sol", "pompe", 3, mods=["pause"], base="Pompes")
E("Pompes PdC", "pompe", 3, doublon="Pompes")
E("Pompes pliométriques (mains sur boxes)", "pompe_explosive", 7, eq=["box"])
E("Pompes prise large", "pompe", 3)
E("Pompes prise serrée", "pompe_diamant", 4)
E("Pompes pseudo-planche", "pompe_pseudo", 6)
E("Pompes spiderman", "pompe", 4, prim="pectoraux triceps obliques")
E("Pompes sur les poings", "pompe", 3, contrainte="21110000", alias=["pompes poings fermés (poignet neutre)"])
E("Pompes surélevées (pieds sur banc)", "pompe_declinee", 4, doublon="Pompes déclinées")
E("Pompes tempo", "pompe", 3, mods=["tempo"], base="Pompes")
E("Pompes typewriter", "pompe_archer", 7)
E("Pompes une main (progression)", "pompe_un_bras", 7, nc="Intitulé « progression » sans étape précise ; interprété comme pompe à un bras mains surélevées.",
  eq=["support_stable"], pose="pompe.inclinee")
E("Pont fessier au sol", "pont_fessier", 1)
E("Pont fessier une jambe", "pont_fessier", 3, uni=True, pose="pont.unijambe")
E("Power clean", "clean", 7)
E("Presse à cuisses", "presse", 2)
E("Pronation / supination haltère", "poignet_rotation", 1)
E("Prone Y raises", "ytw", 2)
E("Pseudo-planche hold", "pseudo_planche_hold", 5)
E("Pull-apart élastique", "pull_apart", 1)
E("Pull-over poulie", "pullover", 2)
E("Push jerk", "push_press", 7, precautions_plus=["technique_prioritaire"])
E("Push press", "push_press", 5)
E("Push press haltères", "push_press", 5, charge="halteres", eq=["halteres"])
# ------------------------------------------------------------------ R
E("Rack pulls", "sdt", 4, prim="lombaires fessiers trapezes", eq=["barre", "rack"])
E("Rameur", "ergo_rameur", 2, nc="Matériel v1 « poids de corps » : ergomètre nécessaire.")
E("Rameur — intervalles 500 m", "ergo_rameur", 5, mods=["intervalles"], base="Rameur", mesure="distance")
E("Relevés de jambes au sol", "relevé_jambes", 3)
E("Repos actif", "marche", 1, role="hors_generateur", type="hors_categorie", nc="Consigne de repos, pas un exercice.")
E("Respiration / cohérence cardiaque", "respiration", 1, role="hors_generateur")
E("Reverse hyper", "hyperextension", 3, prim="fessiers lombaires ischios", eq=["machine"])
E("Rice bucket (seau de riz)", "rice_bucket", 1, eq=["aucun"], nc="Matériel v1 « poids de corps » : un seau de riz est nécessaire.")
E("Rollout barre", "ab_wheel", 7, eq=["barre"])
E("Rotations externes (par haltère)", "rotation_externe", 1, charge="halteres", eq=["halteres"], pose="cable.rotation_ext")
E("Rotations externes élastique", "rotation_externe", 1)
E("Rotations internes élastique", "rotation_externe", 1)
E("Rowing barre penché", "rowing_barre", 4)
E("Rowing haltère appui poitrine", "rowing_appui", 2)
E("Rowing haltère unilatéral (par haltère)", "rowing_halteres", 3, uni=True, doublon="Rowing unilatéral haltère",
  nc="Matériel v1 « barre » pour un rowing à un haltère.")
E("Rowing haltères penché", "rowing_halteres", 3)
E("Rowing kettlebell", "rowing_halteres", 3, charge="kettlebell", eq=["kettlebell"], uni=True)
E("Rowing Meadows", "rowing_barre", 5, uni=True)
E("Rowing Pendlay", "rowing_barre", 5)
E("Rowing T-bar", "rowing_barre", 4)
E("Rowing unilatéral haltère", "rowing_halteres", 3, uni=True)
E("Rows archer barre basse", "rowing_australien", 6, uni=True)
E("Rows aux anneaux", "rowing_anneaux", 3)
E("Rows aux sangles (TRX)", "rowing_anneaux", 3, eq=["sangles"])
E("Rows barre basse pieds surélevés", "rowing_australien", 4, eq=["barre_basse", "support_stable"])
E("Rows une main anneaux", "rowing_anneaux", 6, uni=True)
E("Russian dips", "dips_barres", 7, precautions_plus=["epaule_anterieure"])
E("Russian twists", "russian_twist", 2)
E("Russian twists lestés", "russian_twist", 3, mods=["leste"], base="Russian twists", eq=["medecine_ball"], charge="objet_leste")
# ------------------------------------------------------------------ S
E("Sandbag carry", "sandbag_carry", 3)
E("Sandbag clean", "clean", 5, charge="objet_leste", eq=["sac_leste"])
E("Sandbag squat (bear hug)", "squat_gobelet", 4, charge="objet_leste", eq=["sac_leste"])
E("Sauts à la corde unipodaux", "corde_a_sauter", 4, uni=True)
E("Sauts de mollets (pogo)", "pogo", 3)
E("Sauts en contrebas (depth jumps)", "depth_jump", 7)
E("Scapular pull-ups", "scap_pull", 2)
E("Scapular pull-ups lestés", "scap_pull", 4, mods=["leste"], base="Scapular pull-ups")
E("Scapular push-ups", "scapular_pushup", 1)
E("Serratus push-ups (protraction)", "scapular_pushup", 1, doublon="Scapular push-ups")
E("Shoulder taps en ATR", "atr_taps", 6)
E("Shrimp squat", "shrimp_squat", 7)
E("Shrugs barre", "shrug", 2)
E("Shrugs haltères", "shrug", 2, charge="halteres", eq=["halteres"])
E("Shuttle runs (navettes)", "sprint", 5)
E("Side bend haltère", "side_bend", 2)
E("Sissy squat", "sissy_squat", 6)
E("Sissy squat assisté", "sissy_squat", 4, mods=["assiste"], base="Sissy squat")
E("Sit-ups", "situp", 2)
E("Sit-ups butterfly", "situp", 2)
E("Sit-ups GHD", "situp", 6, eq=["ghd"], precautions_plus=["lombaire"])
E("Skater squat", "skater_squat", 6)
E("Skaters", "skaters", 3)
E("SkiErg", "ergo_ski", 2)
E("Skin the cat", "skin_the_cat", 6)
E("Slam ball", "slam", 3)
E("Sled drag arrière", "sled_pull", 4, prim="quadriceps")
E("Sled pull (traîneau, corde)", "sled_pull", 4)
E("Sled push", "sled_push", 4)
E("Snatch (arraché)", "snatch", 9)
E("Soulevé de terre", "sdt", 5)
E("Soulevé de terre jambes tendues", "sdt_roumain", 5)
E("Soulevé de terre kettlebell", "sdt", 2, charge="kettlebell", eq=["kettlebell"])
E("Soulevé de terre roumain", "sdt_roumain", 4)
E("Soulevé de terre sumo", "sdt", 5, prim="fessiers quadriceps adducteurs")
E("Soulevé de terre trap bar", "sdt", 4, prim="quadriceps fessiers ischios")
E("Soulevé de terre unilatéral haltère", "sdt_unijambe", 5)
E("Sprint", "sprint", 6)
E("Sprint en côte", "sprint", 6)
E("Squat 1 ¼", "squat_barre", 5, mods=["tempo"], base="Back squat")
E("Squat au poids de corps", "squat_pdc", 2)
E("Squat bulgare haltères", "fente_bulgare", 5, charge="halteres", eq=["halteres", "support_stable"], doublon="Fentes bulgares")
E("Squat bulgare lesté (gilet)", "fente_bulgare", 6, mods=["leste"], base="Fentes bulgares")
E("Squat cosaque", "squat_cosaque", 4)
E("Squat endurance @ 70 kg", "squat_barre", 5, mods=["series_longues"], base="Back squat",
  nc="Charge absolue (70 kg) inscrite dans le nom : spécifique au propriétaire.")
E("Squat gobelet", "squat_gobelet", 2)
E("Squat overhead", "squat_overhead", 7)
E("Squat pause", "squat_barre", 5, mods=["pause"], base="Back squat")
E("Squat sauté", "squat_saute", 4)
E("Squat sauté lesté", "squat_saute", 6, mods=["leste"], base="Squat sauté")
E("Squat sumo haltère", "squat_gobelet", 2, charge="halteres", eq=["halteres"])
E("Squat tempo", "squat_barre", 5, mods=["tempo"], base="Back squat")
E("Squat Zercher", "squat_barre", 6, pose="squat.zercher", precautions_plus=["coude"])
E("Squat — walkout lourd", "squat_barre", 6, mods=["singles_lourds"], base="Back squat", mesure="temps",
  alias=["walkout (sortie de rack) lourd"])
E("Step-ups", "step_up", 2)
E("Step-ups hauts (box)", "step_up", 4, eq=["box"], pose="step.haut")
E("Step-ups lestés", "step_up", 3, charge="halteres", eq=["halteres", "support_stable"])
E("Straight-arm pulldown", "straight_arm_pulldown", 2)
E("Suitcase carry", "suitcase_carry", 2)
E("Superman dynamique", "superman", 1, mesure="repetitions")
E("Superman hold", "superman", 1)
E("Support hold anneaux/barres", "support_hold", 3, alias=["support hold aux anneaux"], nc="Deux supports dans une même entrée.")
E("Support hold lesté", "support_hold", 4, mods=["leste"], base="Support hold anneaux/barres")
E("Suspension active (active hang)", "active_hang", 2)
# ------------------------------------------------------------------ T
E("Tapis incliné (marche)", "marche", 2, eq=["ergometre"])
E("Tate press", "barre_front", 3, charge="halteres", eq=["halteres", "banc"])
E("Test 1Rm Back Squat", "squat_barre", 6, role="test", mods=["test_1rm"], base="Back squat", precautions_plus=["effort_maximal"])
E("Test 1RM Développé couché", "developpe_couche", 5, role="test", mods=["test_1rm"], base="Développé couché", precautions_plus=["effort_maximal"])
E("Test 1Rm Dip Lesté", "dips_barres", 7, role="test", mods=["leste", "test_1rm"], base="Dips lestés", precautions_plus=["effort_maximal"])
E("Test 1RM Front squat", "front_squat", 6, role="test", mods=["test_1rm"], base="Front squat", precautions_plus=["effort_maximal"])
E("Test 1Rm Muscle-Up Lesté", "muscle_up", 10, role="test", mods=["leste", "test_1rm"], base="Muscle-up lesté", precautions_plus=["effort_maximal"])
E("Test 1RM Soulevé de terre", "sdt", 6, role="test", mods=["test_1rm"], base="Soulevé de terre", precautions_plus=["effort_maximal"])
E("Test 1Rm Traction Lestée", "traction", 8, role="test", mods=["leste", "test_1rm"], base="Traction lestée", precautions_plus=["effort_maximal"])
E("Test 2 km rameur", "ergo_rameur", 5, role="test", mesure="distance", base="Rameur", precautions_plus=["cardio_intense"])
E("Test 5 km course", "course", 5, role="test", mesure="distance", base="Course à pied (footing)", precautions_plus=["cardio_intense"])
E("Test Cooper 12 min", "course", 5, role="test", base="Course à pied (footing)", precautions_plus=["cardio_intense"])
E("Test max burpees 3 min", "burpee", 6, role="test", base="Burpees", precautions_plus=["cardio_intense"])
E("Test max dead-hang", "dead_hang", 3, role="test", base="Dead-hang")
E("TEST MAX DIPS PdC", "dips_barres", 6, role="test", mods=["test_max_reps"], base="Dips")
E("Test max handstand hold", "atr", 7, role="test", base="ATR (équilibre)")
E("Test max L-sit", "lsit", 5, role="test", base="L-sit")
E("TEST MAX MUSCLE-UPS PdC", "muscle_up", 9, role="test", mods=["test_max_reps"], base="Muscle-up strict")
E("TEST MAX POMPES PdC", "pompe", 4, role="test", mods=["test_max_reps"], base="Pompes")
E("TEST MAX SQUAT @ 70 kg", "squat_barre", 6, role="test", mods=["test_max_reps"], base="Back squat",
  nc="Charge absolue (70 kg) inscrite dans le nom : spécifique au propriétaire.")
E("TEST MAX TRACTIONS PdC", "traction", 6, role="test", mods=["test_max_reps"], base="Traction pronation")
E("Thruster", "thruster", 6)
E("Thruster haltères", "thruster", 5, charge="halteres", eq=["halteres"])
E("Tibialis raises", "tibial", 1)
E("Tirage bûcheron à la barre fixe", "traction_archer", 8, alias=["tirage latéral alterné à la barre (bûcheron)"])
E("Tirage horizontal poulie", "tirage_horizontal_poulie", 2)
E("Tirage horizontal unilatéral poulie", "tirage_horizontal_poulie", 2, uni=True)
E("Tirage menton barre", "tirage_menton", 3)
E("Tirage menton haltères", "tirage_menton", 3, charge="halteres", eq=["halteres"], nc="Groupe v1 « dos » : moteurs deltoïdes et trapèzes.")
E("Tirage vertical prise neutre", "tirage_vertical_poulie", 2)
E("Tirage vertical pronation", "tirage_vertical_poulie", 2)
E("Tirage vertical supination", "tirage_vertical_poulie", 2)
E("Tirage vertical unilatéral", "tirage_vertical_poulie", 3, uni=True)
E("Toes to bar", "toes_to_bar", 6)
E("Toes to bar kipping", "toes_to_bar", 6, precautions_plus=["technique_prioritaire"])
E("Toes to bar strict", "toes_to_bar", 7)
E("Traction à la serviette", "traction", 7, eq=["barre_fixe", "serviette"], prim="grand_dorsal biceps avant_bras")
E("Traction archer", "traction_archer", 8)
E("Traction assistée élastique", "traction_assistee", 3)
E("Traction autour du monde", "traction_archer", 8)
E("Traction aux anneaux", "traction_anneaux", 5)
E("Traction aux anneaux prise neutre", "traction_anneaux", 5, doublon="Traction aux anneaux")
E("Traction commando", "traction", 6)
E("Traction excentrique lestée", "traction_negative", 6, mods=["leste"], base="Traction lestée")
E("Traction explosive", "traction_explosive", 7)
E("Traction haute explosive (high pull-up)", "traction_explosive", 8)
E("Traction isométrique (menton au-dessus)", "traction_iso", 4)
E("Traction isométrique 90°", "traction_iso", 5, pose="suspension.iso90.barre_fixe")
E("Traction L-sit", "traction_l", 7)
E("Traction lestée", "traction", 6, mods=["leste"], base="Traction pronation")
E("Traction lestée cluster", "traction", 6, mods=["leste", "clusters"], base="Traction lestée")
E("Traction lestée élastique (accommodante)", "traction", 7, mods=["leste", "elastique_resistance"], base="Traction lestée",
  eq=["barre_fixe", "lest", "elastique"], nc="Matériel v1 « élastique » seul : barre fixe et lest nécessaires.")
E("Traction lestée pause", "traction", 6, mods=["leste", "pause"], base="Traction lestée")
E("Traction lestée tempo", "traction", 6, mods=["leste", "tempo"], base="Traction lestée")
E("Traction lestée — singles lourds", "traction", 7, mods=["leste", "singles_lourds"], base="Traction lestée")
E("Traction négative lente", "traction_negative", 3)
E("Traction pause haute", "traction", 5, mods=["pause"], base="Traction pronation")
E("Traction poitrine-barre", "traction_poitrine", 6)
E("Traction prise large", "traction", 6)
E("Traction prise mixte", "traction", 5)
E("Traction prise neutre", "traction", 5)
E("Traction prise serrée", "traction", 5)
E("Traction pronation", "traction", 5)
E("Traction sternum", "traction_poitrine", 8)
E("Traction supination", "traction", 5, prim="grand_dorsal biceps", alias=["chin-up"])
E("Traction tempo (3 s excentrique)", "traction", 5, mods=["tempo"], base="Traction pronation")
E("Traction typewriter", "traction_archer", 8)
E("Traction une main (assistée)", "traction_un_bras", 9, mods=["assiste"], base="Traction une main (négative)")
E("Traction une main (négative)", "traction_un_bras", 9, mods=["negatif"])
E("Tractions explosives poitrine-barre", "traction_explosive", 7)
E("Tractions PdC", "traction", 5, doublon="Traction pronation")
E("Transition muscle-up à l'élastique", "muscle_up_transition", 6, doublon="Transitions de muscle-up à l'élastique")
E("Transition muscle-up assistée pieds au sol", "muscle_up_transition", 4, charge="assistance", eq=["barre_basse"])
E("Transitions de muscle-up à l'élastique", "muscle_up_transition", 6)
E("Travail poignet excentrique (haltère)", "poignet_flexion", 1, mods=["negatif"])
E("Tuck jumps", "saut", 5, pose="saut.tuck")
E("Tuck planche", "planche_skill", 7, pose="planche_skill.tuck")
E("Tuck-ups", "v_ups", 3)
E("Turkish get-up", "turkish", 6)
# ------------------------------------------------------------------ V – Z
E("V-sit (tenue)", "vsit", 9)
E("V-sit progression", "vsit", 8, nc="Intitulé « progression » sans étape précise.")
E("V-ups", "v_ups", 4)
E("Vélo — intervalles", "ergo_velo", 4, mods=["intervalles"], base="Echo bike (calories)")
E("Wall balls", "wall_ball", 4)
E("Wall sit (chaise)", "wall_sit", 2)
E("Wall slides (glissés au mur)", "wall_slides", 1)
E("Wall walks", "wall_walk", 5)
E("Windshield wipers (essuie-glaces)", "windshield", 8)
E("Woodchop poulie", "woodchop", 3)
E("Wrist push-ups (poignets)", "mobilite_poignets", 2, pose="planche_gainage.bras_tendus", mesure="repetitions")
E("YTW à plat ventre (banc incliné)", "ytw", 2)
E("YTW allongé", "ytw", 2, eq=["halteres"], doublon="YTW à plat ventre (banc incliné)")
E("Z-press", "developpe_assis", 5, charge="barre", eq=["barre"], pose="press.assis")
E("Barre au front EZ", "barre_front", 3, added=True, nom="Barre au front EZ",
  source_note="Présent dans le pilotage du programme (B35) mais absent de la base v1.")

# ------------------------------------------------------------------ EXERCICES AJOUTÉS (progressions, mobilité, couverture)
E("Pompes au mur", "pompe_mur", 1, added=True)
E("Pompe à un bras", "pompe_un_bras", 9, added=True, eq=["aucun"])
E("Suspension passive pieds au sol", "dead_hang", 1, added=True, charge="assistance", alias=["suspension assistée"])
E("Rowing australien barre haute", "rowing_australien", 2, added=True)
E("Traction lestée lourde", "traction", 8, added=True, mods=["leste"], base="Traction lestée", role="hors_generateur",
  nc="Entrée de palier (lest ≥ 25 % du poids de corps) utilisée uniquement comme étape d'arbre.")
E("Dips sur banc genoux fléchis", "dips_banc_genoux", 2, added=True)
E("Support hold aux barres", "support_hold", 2, added=True)
E("Squat assisté (appui)", "squat_assiste", 1, added=True)
E("Squat sur chaise", "squat_chaise", 1, added=True)
E("Pistol squat sur box", "pistol_box", 6, added=True)
E("Fente statique (split squat)", "fente", 2, added=True)
E("Charnière de hanche au bâton", "charniere_baton", 1, added=True)
E("Soulevé de terre roumain haltères", "sdt_roumain", 3, added=True, charge="halteres", eq=["halteres"])
E("Planche sur les genoux", "planche_genoux", 1, added=True)
E("Ab wheel à genoux (amplitude courte)", "ab_wheel", 4, added=True)
E("Hollow body groupé", "hollow_groupe", 2, added=True)
E("Isométrie de transition muscle-up", "muscle_up_iso", 7, added=True, base="Muscle-up")
E("Planche complète", "planche_skill", 10, added=True, pose="planche_skill.full")
E("Pike hold (V inversé)", "pompe_pike", 2, added=True, type="figure_statique", mesure="temps")
E("L-sit une jambe", "lsit_une_jambe", 4, added=True)
E("Planche latérale sur les genoux", "planche_laterale", 1, added=True)
E("Drapeau vertical (tenue)", "drapeau", 6, added=True, pose="drapeau.vertical")
E("Drapeau straddle", "drapeau", 8, added=True, pose="drapeau.straddle")
E("Cercles de bras", "cercles_bras", 1, added=True)
E("Squat profond tenu", "squat_profond_tenu", 2, added=True)
E("Mobilisation cheville genou au mur", "mobilite_chevilles", 1, added=True)
E("Fente basse étirement (hanche)", "etirement_flechisseurs", 1, added=True)
E("Rowing à la serviette (porte)", "rowing_australien", 2, added=True, eq=["serviette"], pose="rowing.penche",
  precautions_plus=["suspension"], alias=["tirage serviette coincée dans une porte fermée"])
E("Tirage isométrique à la serviette", "traction_iso", 1, added=True, type="tirage_vertical", eq=["serviette"], pose="debout.grip",
  alias=["tirage vertical isométrique serviette"])
E("Tractions australiennes pieds au sol (table)", "rowing_australien", 2, added=True, eq=["support_stable"],
  precautions_plus=["suspension"], alias=["rowing sous une table solide"])
E("Marche en fente", "fente", 2, added=True)
E("Pont fessier marché", "pont_fessier", 2, added=True, mesure="repetitions")
E("Superman W", "superman", 1, added=True, prim="deltoide_posterieur rhomboides lombaires")
E("Gainage anti-rotation en planche (épaules)", "planche_bras_tendus", 3, added=True, type="gainage_anti_rotation", mesure="repetitions")
E("Tirage élastique horizontal", "rowing_australien", 1, added=True, charge="elastique", eq=["elastique"], pose="assis.row")
E("Tirage élastique vertical", "tirage_vertical_poulie", 1, added=True, charge="elastique", eq=["elastique"])
E("Développé élastique au-dessus de la tête", "developpe_halteres", 1, added=True, charge="elastique", eq=["elastique"])
E("Pompes élastique", "pompe", 4, added=True, mods=["elastique_resistance"], base="Pompes", eq=["elastique"])
E("Squat élastique", "squat_pdc", 2, added=True, charge="elastique", eq=["elastique"])
E("Pallof isométrique au partenaire ou à la serviette", "pallof", 1, added=True, charge="poids_de_corps", eq=["serviette"])
E("Pompes lestées lourdes", "pompe", 7, added=True, mods=["leste"], base="Pompes lestées", role="hors_generateur",
  nc="Entrée de palier (lest ≥ 20 % du poids de corps) utilisée uniquement comme étape d'arbre.")
E("Dips lestés lourds", "dips_barres", 8, added=True, mods=["leste"], base="Dips lestés", role="hors_generateur",
  nc="Entrée de palier (lest ≥ 30 % du poids de corps) utilisée uniquement comme étape d'arbre.")
# Ajouts de couverture « maison sans matériel » (manques de la matrice KT-048)
E("Pompes pike sur les genoux", "pompe_pike", 3, added=True)
E("Soulevé de terre sur une jambe au poids de corps", "sdt_unijambe", 4, added=True, charge="poids_de_corps", eq=["aucun"])
E("Hip thrust une jambe (épaules sur une chaise)", "hip_thrust", 4, added=True, charge="poids_de_corps", eq=["support_stable"], uni=True)
E("Planche bras et jambe opposés levés", "planche_bras_tendus", 4, added=True, type="gainage_anti_rotation", mesure="repetitions")
E("Planche de l'ours avec touchers d'épaules", "crawl", 4, added=True, type="gainage_anti_rotation", mesure="repetitions",
  pose="quadrupedie.bear_crawl")
E("Planche latérale bras tendu", "planche_laterale", 3, added=True, contrainte="21100100")
E("Planche latérale avec abduction de jambe", "planche_laterale", 5, added=True, prim="obliques moyen_fessier")
